### ISSUE TITLE
One hot encoding, pair wise Correlation greater than .7

### ISSUE THREAD

**Issue by aguptaz** [aakashjhawar/AnalyticsVidhya-India-ML-Hiring-Hackathon-2019#2]
Hi Aakash,
i was going through you code, i have few queries ,why you have not used One hot encoding after label encoding. 2nd question is as i saw you have not removed feature with pairwise correlation if value greater than .7  . Can you explain this please.

**Comment by aakashjhawar** [comment]
Hi Amit,
I tried One Hot Encoding on some of the columns like 'source' and 'loan_purpose' and removed the columns which were highly correlated to other columns ('number_of_borrowers' & 'co-borrower_credit_score'),  but the accuracy decreased after performing the above steps. So, I decided to skip One Hot Encoding and not removing any columns.
